services:
  backend:
    image: "$LOCAL_IMAGE_NAME"
    ports:
      - "8080:8080"
    environment:
      - PREDICTIONS_STREAM_NAME=ride_predictions
      - RUN_TEST=True
      - RUN_ID=Test123
      - AWS_DEFAULT_REGION=us-west-2
      - MODEL_LOCATION=/app/model
    volumes:
      - "./model:/app/model"
  kinesis:
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

more-env:
  - LOCALSTACK_SERVICES=s3
  - DEFAULT_REGION=us-east-2
      
