# config file version
apiVersion: 1

# list of datasources to insert/update
# available in the database
datasources:
  - name: NewPostgreSQL
    type: postgres
    url: db:5432
    database: postgres
    user: postgres
    secureJsonData:
      password: 'example'
    jsonData:
      sslmode: 'disable'
      database: test
